services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fulbo
      POSTGRES_PASSWORD: fulbo123
      POSTGRES_DB: fulbo_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
